apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/service-type: "managed"
  annotations:
    prometheus.io/port: "{{ .Values.port  }}"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{ .Values.port }}
    name: metrics
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
