apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" }}
  namespace: {{ include "resource.default.namespace" }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/service-type: "managed"
  annotations:
    prometheus.io/port: "{{ .Values.port  }}"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
    # TODO: decide if this is needed
    # giantswarm.io/monitoring-path: "metrics"
    # giantswarm.io/monitoring-port: "{{ .Values.port  }}"
    # giantswarm.io/monitoring: "true"
spec:
  ports:
  - port: {{ .Values.port }}
    name: metrics
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
