# Default values for node-exporter-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

name: node-exporter
namespace: kube-system
port: 10300

# Run as root user to get proper permissions
userID: 0
groupID: 0

image:
  registry: docker.io
  name: giantswarm/node-exporter
  tag: v1.0.1-giantswarm

resources:
  limits:
    memory: 75Mi
  requests:
    cpu: 75m
    memory: 50Mi

test:
  image:
    registry: docker.io
    repository: giantswarm/alpine-testing
    tag: 0.1.0

isManagementCluster: false
registry:
  domain: docker.io
