checks:
  exclude:
    # Node exporter requires host access to collect system metrics
    - host-network
    - host-pid
    - sensitive-host-mounts
    # No anti-affinity needed for DaemonSet (runs on all nodes)
    - no-anti-affinity
    # Upstream node-exporter container configuration
    - no-read-only-root-fs

