name: Changelog link
on:
  push:
    branches-ignore:
      - 'legacy#*'
      - '*#release#*'
      - 'release#*'
jobs:
  debug_info:
    name: Debug info
    runs-on: ubuntu-20.04
    steps:
      - name: Print github context JSON
        run: |
          cat <<EOF
          ${{ toJson(github) }}
          EOF
  add_changelog_link:
    name: Add changelog link
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Unreleased changelog entries
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: "Unreleased"
          path: ./CHANGELOG.md
      - name: Add changelog link
        id: add_changelog_link
        run: |
          branch="${{ github.event.ref }}"
          branch="${branch#refs/heads/}" # Strip "refs/heads/" prefix.

          # Authenticate gh
          gh auth login --with-token <<<$(echo -n ${{ secrets.GITHUB_TOKEN }})

          # Fetch base branch
          base=$(gh pr view --repo ${{ github.repository }} "$branch" --json baseRefName --jq .baseRefName)
          git fetch origin "$base"

          # Get changed line in CHANGELOG
          lines=$(git diff --no-prefix -U0 $(git merge-base HEAD origin/${{ github.event.repository.default_branch }})..HEAD -- CHANGELOG.md|tail +6|awk -F'^[+]' '{print $2}')

          # Skip when no changes are detected
          # Skip when more than 1 line are changed #Remove maybe?
          echo "$lines"|wc -l
          if [[ $(echo "$lines" | wc -l) -ne 1 ]]; then
            echo "> skipping changelog link update; no or too many detected lines"
            exit 0
          fi

          # Skip when change line is not part of the unreleased changelog entries
          if ! echo "${{ steps.changelog_reader.outputs.changes }}" | grep -q "$lines"; then
            echo "> skipping changelog link; detected line not from unreleased entries"
            exit 0
          fi

          # Skip when changelog link was already added
          if echo "$lines" | grep -qE '\s\(#[[:digit:]]+\)$'; then
            echo "> skipping changelog link; link already added"
            exit 0
          fi

          # Get PR link
          pr_number=$(gh pr view --repo ${{ github.repository }} "$branch" --json number --jq .number)

          echo "$lines"
          sed --version
          set -x
          sed -i 's/'"$lines"'/'"$lines (#$pr_number)"'/' CHANGELOG.md
      - name: Set up git identity
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit changes
        run: |
          git add CHANGELOG.md
          git commit -m "add pull request reference in changelog"
      - name: Push changes
        env:
          remote_repo: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        run: |
          git push "${remote_repo}" HEAD:${{ github.event.ref }}
  push_changes:
    name: Push changes
    runs-on: ubuntu-20.04
    needs:
      - add_changelog_link
    steps:
      - name: Placeholder
        run: |
          echo placeholder
